skt:
  multi-datasource:
    datasource2:
      #      initialize: false
      initializationMode: NEVER
      type: org.apache.commons.dbcp2.BasicDataSource
      dbcp2:
        default-auto-commit: false
        driver-class-name: org.mariadb.jdbc.Driver
        test-on-borrow: true
        username: root
        password: root
        initial-size: 5
        default-query-timeout: 60000
        url: jdbc:mariadb://localhost:3307/leafCat
        max-idle: 20
        max-total: 20
        validation-query: select 1
        max-wait-millis: 30000
        max-open-prepared-statements: 20