apiVersion: v1
kind: Service
metadata:
  name: classic-web
  # prometheus metric
  labels:
    app: classic-web
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "8090"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    # jmx exporter
    - name: jmx-exporter
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: classic-web
    version: 0.0.1
  type: ClusterIP